export {
  BotConfigSchema,
  GridBotPairSchema,
  MarketMakerPairSchema,
  AdaptiveMMPairSchema,
  ArbitragePoolSchema,
  RPCConfigSchema,
  PersistenceConfigSchema,
  RiskConfigSchema,
  ClaudeConfigSchema,
  ArbitrageConfigSchema,
  ClaudeAdaptiveMMConfigSchema,
  StrategyConfigSchema,
  MonitoringConfigSchema,
  validateConfig,
  validatePartialConfig,
  getDefaultConfig,
  type GridBotPair,
  type MarketMakerPair,
  type AdaptiveMMPair,
  type ArbitragePool,
  type RPCConfig,
  type PersistenceConfig,
  type RiskConfig,
  type ClaudeConfig,
  type ArbitrageConfig,
  type ClaudeAdaptiveMMConfig,
  type StrategyConfig,
  type MonitoringConfig,
  type BotConfig
} from './schema.js';
